# Generated by Django 5.1.1 on 2024-09-16 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('schema_match', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schema_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModifiedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_content', models.JSONField()),
                ('column_mapping', models.JSONField(default=dict)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.fileupload')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
